Update pass policy mega script

diff --git a/pass policy mega script b/pass policy mega script
--- a/pass policy mega script
+++ b/pass policy mega script
@@ -1,35 +1,63 @@
-#! /bin/bash
+#!/bin/bash
 
-function main {
-  echo "Making a backup login.defs file..."
-  cp /etc/login.defs /etc/login.defs~
-  chmod a-w /etc/login.defs~
-
-  echo "Copying local login.defs file..."
-  cp ../resources/my_login.defs /etc/login.defs
-  nano /etc/login.defs
-
-  #common-password
-  echo "Making a backup config file..."
-  cp /etc/pam.d/common-password /etc/pam.d/common-password~
-  chmod a-w /etc/pam.d/common-password~
-
-  echo "Copying local common-password file..."
-  cp ../resources/my_common-password /etc/pam.d/common-password
-  nano /etc/pam.d/common-password
-
-  sudo apt install libpam-pwquality
-  sudo sed -i 's/password requisite pam_pwquality.so retry=3/password requisite pam_pwquality.so retry=3 minlen=10 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1/' /etc/security/pwquality.conf
-  echo 'Password policies configured' >> checklist.txt
-}
-
-#actually running the script
-unalias -a #Get rid of aliases
-echo "unalias -a" >> /root/.bashrc # gets rid of aliases when root
-cd $(dirname $(readlink -f $0))
+# Ensure the script is executed with root privileges
 if [ "$(id -u)" != "0" ]; then
-  echo "Please run as root"
-  exit
-else
-  main
+  echo "Please run this script as root."
+  exit 1
 fi
+
+echo "Making a backup login.defs file..."
+cp /etc/login.defs /etc/login.defs~
+chmod a-w /etc/login.defs~
+
+echo "Copying local login.defs file..."
+cp ../resources/my_login.defs /etc/login.defs
+nano /etc/login.defs
+
+#common-password
+echo "Making a backup config file..."
+cp /etc/pam.d/common-password /etc/pam.d/common-password~
+chmod a-w /etc/pam.d/common-password~
+
+echo "Copying local common-password file..."
+cp ../resources/my_common-password /etc/pam.d/common-password
+nano /etc/pam.d/common-password
+
+# Define policy parameters
+MIN_PASSWORD_LENGTH=12
+MAX_DAYS=90
+MIN_DAYS=7
+WARN_DAYS=7
+MAX_TRIES=3
+
+# Install necessary packages
+apt-get update
+apt-get install -y libpam-pwquality
+
+# Set password complexity requirements
+echo "password requisite pam_pwquality.so retry=$MAX_TRIES minlen=$MIN_PASSWORD_LENGTH ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1" >> /etc/security/pwquality.conf
+
+# Set password expiration policy
+sed -i "/^PASS_MAX_DAYS/c\PASS_MAX_DAYS $MAX_DAYS" /etc/login.defs
+sed -i "/^PASS_MIN_DAYS/c\PASS_MIN_DAYS $MIN_DAYS" /etc/login.defs
+sed -i "/^PASS_WARN_AGE/c\PASS_WARN_AGE $WARN_DAYS" /etc/login.defs
+
+# Enable account lockout
+echo "auth required pam_tally2.so onerr=fail deny=$MAX_TRIES unlock_time=1800" >> /etc/pam.d/common-auth
+echo "account required pam_tally2.so" >> /etc/pam.d/common-account
+
+# Enforce password history (remember previous passwords)
+echo "password required pam_pwhistory.so remember=5" >> /etc/pam.d/common-password
+
+# Lock inactive accounts after a specified period
+useradd -D -f 30
+
+# Display message when account is locked
+echo "account [default=bad success=ok user_unknown=ignore] pam_unix.so" >> /etc/pam.d/common-account
+echo "account requisite pam_deny.so" >> /etc/pam.d/common-account
+echo "account required pam_permit.so" >> /etc/pam.d/common-account
+
+# Optionally, configure password aging for individual users using the 'chage' command
+
+# Ensure the changes take effect
+echo "Password and account policies configured. Please restart your system for changes to take effect."
